---
title: "R第四次实训"
output: html_notebook
---
#题目3
###3.1
#####3.1.1 通过读取文件outcome-of-care-measures.csv获取数据保存到care_df中
#####3.1.2 通过写一个名为 best的函数，找到一个州中最好的医院，函数有两个参数，一个是有两个字母缩写的州名称，另一个是结果名称，包括（heart attack, heart failure, pneumonia），函数的返回结果为30天死亡率最低的医院名称。在处理排名的时候，如果出现死亡率相等的情况，将医院按照字母表顺序排序，取第一家医院
```{r}
care_df <- read.csv("outcome-of-care-measures.csv",na.strings="Not Available") #3.1.1
care_df
```
```{r}
best <- function(state,outcome){ #3.1.2
  ccdf <- care_df[care_df$State==state,]
  outcomeset <- c("heart attack", "heart failure", "pneumonia")
  if(dim(ccdf)[1] == 0)
    return ("invalid state")
  if(length(unique(c(outcome,outcomeset))) > 3)
    return ("invalid outcome")
  li <- gsub(" ",".",outcome)
  cdf <- data.frame(
    hospital=ccdf$Hospital.Name,
    state=ccdf$State,
    heart.attack=ccdf[,11],
    heart.failure=ccdf[,17],
    pneumonia=ccdf[,23]
  )
  cdf <- cdf[c("hospital",li)]
  cdf[is.na(cdf[,2]),2] <- 100
  return (min(as.character(cdf[which.min(cdf[,2]),1])))
}
best("TX", "heart failure")
best("MD", "heart attack")
best("MD", "pneumonia")
best("BB", "heart attack")
best("NY", "hert attack")
```

